### ISSUE TITLE
Error registering event handler for multiblock format event

### ISSUE THREAD

**Issue by KylePoe** [FerroO2000/Immersive-Tech#101]
Hi all, I got the following error in my forge server install log.

`[18:54:51] [Server thread/ERROR] [FML]: Error registering event handler: FMLMod:immersivepetroleum{1.1.9} class blusunrize.immersiveengineering.api.MultiblockHandler$MultiblockFormEvent public void flaxbeard.immersivepetroleum.common.items.ItemProjector.handleMultiblockComplete(blusunrize.immersiveengineering.api.MultiblockHandler$MultiblockFormEvent)
java.lang.InstantiationException: null
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:1.8.0_252]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_252]
        at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:130) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112) [EventBus.class:?]
        at flaxbeard.immersivepetroleum.common.items.ItemProjector.<init>(ItemProjector.java:73) [ItemProjector.class:?]
        at flaxbeard.immersivepetroleum.common.IPContent.preInit(IPContent.java:146) [IPContent.class:?]
        at flaxbeard.immersivepetroleum.ImmersivePetroleum.preInit(ImmersivePetroleum.java:55) [ImmersivePetroleum.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[18:54:51] [Server thread/ERROR] [immersiveengineering]: WireType#init was called by Immersive Tech (immersivetech)!
[18:54:51] [Server thread/ERROR] [immersiveengineering]: The method should only be called by Immersive Engineering, calls from other mods will cause many hard-to-debug issues and are therefore forbidden!
[18:54:51] [Server thread/ERROR] [immersiveengineering]: Please report this as a bug to Immersive Tech`

Forge version: forge-1.12.2-14.23.5.2847-universal.jar
Minecraft version: 1.12.2
Context: [MC Eternal serverpack 1.3.7.1](https://www.curseforge.com/minecraft/modpacks/minecraft-eternal)

Not sure how this will manifest in gameplay, but I will update when I know.

**Comment by tgstyle** [comment]
Have you tried Immersive Technology instead of Immersive Tech?
This project is pretty much abandoned.
https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology

**Comment by chriptus13** [comment]
Same error here with [Levitated 1.4.1 Modpack](https://www.curseforge.com/minecraft/modpacks/levitated).
